# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "cloud.google.com/go"
  version = "0.18.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.70"

[[constraint]]
  branch = "master"
  name = "github.com/dustin/go-humanize"

[[constraint]]
  branch = "master"
  name = "github.com/garyburd/go-oauth"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3.0"

[[constraint]]
  name = "github.com/google/go-github"
  version = "15.0.0"

[[constraint]]
  name = "github.com/gorilla/securecookie"
  version = "1.1.0"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/kjk/lzmadec"

[[constraint]]
  branch = "master"
  name = "github.com/kjk/simplenote"

[[constraint]]
  branch = "master"
  name = "github.com/kjk/stackoverflow"

[[constraint]]
  branch = "master"
  name = "github.com/kjk/u"

[[constraint]]
  name = "github.com/speps/go-hashids"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/syndtr/goleveldb"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"

[prune]
  go-tests = true
  unused-packages = true
