---
- name: deploy quicknotes
  hosts: quicknotes
  tasks:
  - name: get repo sha1
    local_action: command ../get-sha1.sh
    register: sha1
  - name: build
    local_action: command python build.py
  - name: stop currently running
    command: systemctl stop quicknotes
    sudo: yes
    ignore_errors: yes
  - name: create systemd file
    copy: src=quicknotes.service dest=/lib/systemd/system/quicknotes.service owner=root group=root mode=0644
    sudo: yes
  - name: make changes to quicknotes.service visible
    command: systemctl daemon-reload
    sudo: yes
  - name: enable the service so that it restarts on reboot
    command: systemctl enable quicknotes
    sudo: yes
  - name: create directory for the app
    file: >
      path=/home/quicknotes/www/app/{{ sha1.stdout }}
      state=directory mode=0755
      owner=quicknotes group=quicknotes
  - name: create directory for app's log
    file: >
      path=/home/quicknotes/www/data/log
      state=directory mode=0755
      owner=quicknotes group=quicknotes
  - name: create directory for app's localstore
    file: >
      path=/home/quicknotes/www/data/localstore
      state=directory mode=0755
      owner=quicknotes group=quicknotes
  - name: unzip files
    unarchive: src={{ sha1.stdout }}.zip dest=/home/quicknotes/www/app/{{ sha1.stdout }}
  - name: stat current
    stat: path=/home/quicknotes/www/app/current
    register: current_stat
  - name: remove old prev directory
    file: path=/home/quicknotes/www/app/prev state=absent
  - name: rename current to prev
    command: mv current prev
    when: current_stat.stat.exists
    args:
      chdir: /home/quicknotes/www/app
  - name: symlink sha1 to current
    file: >
      src=/home/quicknotes/www/app/{{ sha1.stdout }}
      dest=/home/quicknotes/www/app/current
      state=link
  - name: start it
    command: systemctl start quicknotes
    sudo: yes
  - name: delete .zip file
    local_action: command rm {{ sha1.stdout }}.zip
  - name: show status
    command: systemctl status quicknotes
    sudo: yes
    register: quicknotes_status
  - debug: var=quicknotes_status.stdout_lines
